# -*- coding: utf-8 -*-
"""AI-conversation-agent.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IU7yT6In-tLD40EL4ze0UuM0rX-T_6k5
"""



from transformers import BlenderbotTokenizer, BlenderbotForConditionalGeneration
import gradio as gr

model_name = "facebook/blenderbot-400M-distill"

model = BlenderbotForConditionalGeneration.from_pretrained(model_name)
tokenizer = BlenderbotTokenizer.from_pretrained(model_name)

def func(message):
   inputs = tokenizer([message], return_tensors='pt')
   reply_ids = model.generate(**inputs)
   return tokenizer.batch_decode(reply_ids)

descriptions = "This is a conversational AI, have a conversation with it. built by EDEM GOLD.🚀"

app = gr.Interface(fn=func, inputs="text", outputs="text", title="🤖", description=descriptions)
app.launch()



